[project]
name = "graph-closure-prob-algorithms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "networkx>=3.6",
    "pandas>=2.3.3",
]
